--- # Playbook for removing CivCRM  from a server.
- hosts: testserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  roles:
    - { role: remove.civcrm, php_packages_state: absent }