- name: Drupal | Install needed PHP extensions.
  package: name={{ item }} state=latest
  with_items:
    - php-mysql
    - php-zip

- name: Drupal | Checkout via Drush.
  shell: drush dl drupal-7 --drupal-project-rename={{ project_name }} --destination={{ www_dir }}

- name: CiviCRM | Install needed modules and files directories.
  unarchive:
    src: "drupal/{{ item }}.tar.bz2"
    dest: "{{ project_dir }}"
  with_items:
    - drupal-modules
    - civicrm-files

- name: Drupal | Copy configuration files.
  template:
    src: "drupal/{{ item }}.php.j2"
    dest: "{{ project_dir }}/sites/default/{{ item }}.php"
    owner: www-data
    group: www-data
    mode: 0644
  with_items:
    - settings
    - civicrm.settings

- name: Drupal | Copy .htaccess file.
  template:
    src: drupal/.htaccess.j2
    dest: "{{ project_dir }}/sites/default/files/.htaccess"
    owner: www-data
    group: www-data
    mode: 0644

- name: Drupal | Unarchive DB dumps.
  unarchive:
    src: "drupal/{{ item.name }}.sql.tar.bz2"
    dest: /tmp
  with_items:
    - "{{ databases }}"

- name: Drupal | Import drupal and civicrm databases.
  mysql_db:
    state: import
    name: "{{ item.name }}"
    target: "/tmp/{{ item.name }}.sql"
    login_user: root
    login_password: "{{ db_root_password }}"
  with_items:
    - "{{ databases }}"

- name: Drupal | Create logs dir for the cron.
  file:
    path: "{{ project_dir }}/logs"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Drupal | Install cron for Drupal.
  cron:
    job: "wget -O - -q -t 1 https://{{ server_domain }}/cron.php?cron_key=tayVa4xo5Bg0yv6uyHMWwJae1Pwgq6Ij_YcXX60PLzk"
    name: "drupal-cron"
    state: present
    user: www-data
    minute: "*/5"

- name: Drupal | Install cron for CiviCRM.
  cron:
    job: "/usr/local/bin/drush -r /var/www/compucorp -l https://{{ server_domain }} civicrm-api -u {{ civicrm_cron_user }} job.execute > {{ project_dir }}/logs/cron.status.log"
    name: "civicrm-cron"
    state: present
    user: www-data
    minute: "*/5"

- name: Drupal Backup | Install amazon-s3-php library.
  git:
    repo: 'https://github.com/tpyo/amazon-s3-php-class.git'
    dest: "{{ project_dir }}/sites/all/libraries/s3-php5-curl"
    version: 'v0.5.1'

- name: Drupal | Set permissions for www-data to be able to install Drupal.
  file:
    path: "{{ project_dir }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: 0755

