--- # Main tasks.
- name: Setup | Copy uninstall script.
  copy:
    src: uninstall.sh
    dest: /home/ubuntu/uninstall.sh
    owner: ubuntu
    group: ubuntu
    mode: 0700

- include: install.nginx.yml
- include: install.mysql.yml
- include: install.drupal.yml

# - name: Install CiviCRM via web interface using https://wiki.civicrm.org/confluence/display/CRMDOC/Installing+CiviCRM+for+Drupal+7
# - name: Fix CiviCRM images and script weren’t loading to due the amazon ec2 domain being present in the sites/default/civicrm.settings.php file.
# - name: Fix Drupal and CiviCRM security warnings.
# - name: Install Views3 via web interface?!
# - name: Install needed crons.
# - name: Backup the database
#   - install the needed external library
#   - manually create the backup via web interface

