--- # Main tasks.
- name: Copy uninstall script.
  copy:
    src: uninstall.sh
    dest: /home/ubuntu/uninstall.sh
    owner: ubuntu
    group: ubuntu
    mode: 0700

- include: install.nginx.yml
- include: install.mysql.yml

- name: Drupal | Checkout via Drush.
  shell: drush dl drupal-7 --drupal-project-rename={{ project_name }} --destination={{ root_dir }}

- name: Drupal | Set permissions for www-data to be able to install Drupal.
  file:
    path: "{{ root_dir }}/{{ project_name }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: 0755

- name: Drupal | Check whether file exists.
  shell: ls "{{ root_dir }}/{{ project_name }}/sites/default/settings.php"
  register: file_exists

- name: Drupal | Copy default.settings.php to settings.php.
  copy:
    src: "{{ root_dir }}/{{ project_name }}/sites/default/default.settings.php"
    dest: "{{ root_dir }}/{{ project_name }}/sites/default/settings.php"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0644
  when: file_exists.failed is defined

- name: Drupal | Follow the installation script.
  pause:
    prompt: Go follow the installation steps manually. Press "Ctrl + C" when done.

# - name: Install drupal via Drush.
# - name: Setup Drupal for the first time.
# - name: Install CiviCRM via web interface using https://wiki.civicrm.org/confluence/display/CRMDOC/Installing+CiviCRM+for+Drupal+7
# - name: Fix CiviCRM images and script weren’t loading to due the amazon ec2 domain being present in the sites/default/civicrm.settings.php file.
# - name: Fix Drupal and CiviCRM security warnings.
# - name: Install Views3 via web interface?!
# - name: Install needed crons.
# - name: Backup the database
#   - install the needed external library
#   - manually create the backup via web interface

