--- # Main tasks.
- name: Setup | Copy uninstall script.
  copy:
    src: uninstall.sh
    dest: /home/ubuntu/uninstall.sh
    owner: ubuntu
    group: ubuntu
    mode: 0700

- include: install.nginx.yml
- include: install.mysql.yml
- include: install.drupal.yml
