--- # Defaults for CiviCRM
server_domain: yoyosan.tk
root_dir: /var/www
project_name: compucorp

databases:
  - name: drupal
    user: "{{ db_drupal_user }}"
    password: "{{ db_drupal_password }}"
    privs: "drupal.*:ALL"
  - name: civicrm
    user: "{{ db_civicrm_user }}"
    password: "{{ db_civicrm_password }}"
    privs: "civicrm.*:ALL"